blank_issues_enabled: false
contact_links:
  - name: FAQ and guidelines (Important)
    url: https://github.com/Samillion/ModernZ/blob/main/docs/FAQ.md
    about: Frequent questions are answered there, also includes useful guidelines
  - name: Discussions and Questions
    url: https://github.com/Samillion/ModernZ/discussions
    about: A place to discuss or ask a general question regarding ModernZ osc
