#!/bin/sh
export PATH="$HOME/.config/rofi/my_scripts:$PATH"
# if pgrep -x rofi; then
  # pkill -x rofi
# else
  # ~/.config/rofi/scripts/launcher_t1 -sorting-method fzf -sort -matching fuzzy
  # # rofi -normal-window -show drun
# fi

pkill -x rofi || ~/.config/rofi/scripts/launcher_t1 -sorting-method fzf -sort -matching fuzzy


