[general]
import = [
    # "~/.config/alacritty/themes/themes/aura.toml"
    "~/.cache/wal/colors-alacritty.toml",
    # "colors.toml"
]
# import = ["colors.toml"]
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11  # Adjust size as needed

[window]
padding = { x = 10, y = 10 }  # Adjust padding as needed
opacity = 0.80  # Transparency (0.0 = fully transparent, 1.0 = fully opaque)
blur = true  # Enable background blur (Requires compositor like picom)

[colors]
draw_bold_text_with_bright_colors = true
